#!/bin/bash
# Bash script to test performance and accuracy of C expm (utilising openBLAS & LAPACK) compared to Pythons numpy expm

# compile the C expm shared library:
nvcc --shared -Xcompiler -fPIC -shared expm_single.cu -o ctestcuda.a -lcublas -lcusolver -O3

# Create file and containing folder holding results:
touch Bulk_Results_Serial.txt
results_filename="Bulk_Results_Cuda.txt"
> $results_filename

# Loop through increasing matrix sizes:
for length in 2 4 8 16 32 64 128 256
do
	python3 test.py $length $results_filename  # Run

done
